[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
requires-python = ">=3.7"
name = "extractor"
version = "0.0.1"
dependencies = ["rdkit", "matchms", "numpy", "pandas", "requests", "jupyter", "pytest"]

[project.scripts]
clean = "extractor.extractor:clean"
geninput = "extractor.extractor:generate_gnps_input"
send = "extractor.sender:send"
gensummary = "extractor.extractor:generate_summary"
genarticle = "extractor.extractor:generate_article_data"

[tool.hatch.envs.default.scripts]
test = "pytest {args:tests}"
